name: run-tests

'on':
  push:
    branches:
      - master
      - develop
    tags:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 8 1 * *'

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
      - run: composer install --dev
      - name: php-${{matrix.php-version}}
        run: ./vendor/bin/phpunit
