name: run-tests

'on':
  push:
    branches:
      - master
      - develop
    tags:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 8 1 * *'

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
        dependency-versions:
          - "lowest"
          - "highest"
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Install composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependency-versions }}
      - run: ./vendor/bin/phpunit
